
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int print = 16;
  public static final int ACCFE = 13;
  public static final int PF = 7;
  public static final int ACCOU = 12;
  public static final int EOF = 0;
  public static final int EGAL = 10;
  public static final int ADD = 2;
  public static final int CLR = 15;
  public static final int ID = 9;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int AT = 14;
  public static final int PO = 6;
  public static final int VIRG = 11;
  public static final int MUL = 4;
  public static final int SOU = 3;
  public static final int NB = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "SOU",
  "MUL",
  "DIV",
  "PO",
  "PF",
  "NB",
  "ID",
  "EGAL",
  "VIRG",
  "ACCOU",
  "ACCFE",
  "AT",
  "CLR",
  "print"
  };
}

